id: I9C8B5063
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T06:47:13+00:00'
last_modified: '2022-06-08T09:09:34.494922+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23427
  title: བོན་པོའི་ཡིག་ཆ་ལས་ཚད་མའི་སྐོར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    DBE9:
      image_group_id: I1589
      title: ''
      total_pages: 390
      order: 1
      base_file: DBE9.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
